// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp63Ccxi552Xo2xlCwukQnTHPJHKsfBl0',
    appId: '1:885716601960:web:3b66f5ce8ccd2ae316bfdd',
    messagingSenderId: '885716601960',
    projectId: 'fir-flutter-12a59',
    authDomain: 'fir-flutter-12a59.firebaseapp.com',
    storageBucket: 'fir-flutter-12a59.appspot.com',
    measurementId: 'G-RWHFJ2XT7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqzlpYKkhDDvZwT_k9GVtyNYXgkw6dI7Y',
    appId: '1:885716601960:android:6402d9901936c4dc16bfdd',
    messagingSenderId: '885716601960',
    projectId: 'fir-flutter-12a59',
    storageBucket: 'fir-flutter-12a59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9zK7rXSLO619D9tFfPqcUstZcklwb-vc',
    appId: '1:885716601960:ios:1a3f9c9d7d0b2c3416bfdd',
    messagingSenderId: '885716601960',
    projectId: 'fir-flutter-12a59',
    storageBucket: 'fir-flutter-12a59.appspot.com',
    androidClientId: '885716601960-5118biokvrhr46ajvi0q6uon6momcf4o.apps.googleusercontent.com',
    iosClientId: '885716601960-lr5b18viuflr4b0la1stfmei6buim4cl.apps.googleusercontent.com',
    iosBundleId: 'com.broadwayinfosys.firebaseFlutter',
  );
}
